### ISSUE TITLE
Le Callback MQTT Callback ne remonte pas les valeur dans Home Assistant

### ISSUE THREAD

**Issue by furynick** [yoctopuce/VirtualHub-4web#1]
J'ai suivi le tuto ["Utiliser un yocto-watt  dans home assistant"](http://www.yoctopuce.com/FR/article/utiliser-un-yocto-watt-dans-home-assistant) mais bien que les appareils soient correctement créés, aucune valeur n'est captée par Home Assistant.

![image](https://github.com/yoctopuce/VirtualHub-4web/assets/3520080/c2a38b92-2674-416e-a4d3-4198d85373fd)

L'analyse du trafic réseau (tcpdump) montre bien l'activité du callback
```
09:21:55.563587 IP virtualhub.local.39802 > homeassistant.local.1883: Flags [P.], seq 30847:30877, ack 10, win 251, options [nop,nop,TS val 969940672 ecr 3816118571], length 30
E..R..@.@......y.....z.[h.]..=.r.....
.....
9....uY+0...yocto/Diagramm/power12.679
09:21:55.564017 IP homeassistant.local.1883 > virtualhub.local.39802: Flags [.], ack 30877, win 249, options [nop,nop,TS val 3816118971 ecr 969940672], length 0
E..4..@.?..........y.[.z.=.rh.]......K.....
.uZ.9...
```

Les paramètres sont les suivants :
![image](https://github.com/yoctopuce/VirtualHub-4web/assets/3520080/600c368c-544f-401a-a0ef-7772e800814e)

Les sujets sont bien présents dans MQTT et les données évoluent :
![image](https://github.com/yoctopuce/VirtualHub-4web/assets/3520080/a5cac2dd-4bb5-4092-9d9d-70aee1a5494e)

Le déclenchement du beacon est opérationnel depuis HA.

Le format des données envoyées par le Callback est-il compatible avec Home Assistant ?
Y a-t-il un paramètre du Callback qui soit erroné dans ma configuration ?
Y a-t-il d'autres paramètres côté Home Assistant à modifier ?

Apparemment HA recherche les valeurs dans le sujet /avg
![image](https://github.com/yoctopuce/VirtualHub-4web/assets/3520080/ce7c1ca2-92fe-4ce0-b74d-f7f99d0d4077)

**Comment by srinsoz** [comment]
Il faut activer les timed reports à la fréquence désirée pour l'envoi des informations sur MQTT. 
Vous pouvez consulter cet article pour plus de détails sur les "timed reports" :
https://www.yoctopuce.com/FR/article/les-notifications-periodiques-et-mqtt

**Comment by furynick** [comment]
Effectivement, la remontée des valeurs est opérationnelle, merci pour la réactivité !

Peut-être qu'il serait utile de le mentionner dans le tuto Yocto-Watt pour que le profane comme moi ait toutes les infos au même endroit.
